#!/bin/sh

dotnet csharpier check .
DOTNET_CSHARPIER_EXIT=$?
if [ $DOTNET_CSHARPIER_EXIT -ne 0 ]; then
    echo "❌ CSharpier check failed!"
    echo "💡 Run 'dotnet csharpier format .' to fix formatting issues."
    echo ""
    exit 1
fi

dotnet format --verify-no-changes
DOTNET_FORMAT_EXIT=$?
if [ $DOTNET_FORMAT_EXIT -ne 0 ]; then
    echo ""
    echo "❌ dotnet format check failed!"
    echo "💡 Run 'dotnet format' to fix formatting issues."
    echo ""
    exit 1
fi

exit 0
