//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Atlas.Exceptions.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ExceptionMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ExceptionMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Atlas.Exceptions.Resources.ExceptionMessages", typeof(ExceptionMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The article can&apos;t be null..
        /// </summary>
        public static string ArticleCantBeNull {
            get {
                return ResourceManager.GetString("ArticleCantBeNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The category can&apos;t be null..
        /// </summary>
        public static string CategoryCantBeNull {
            get {
                return ResourceManager.GetString("CategoryCantBeNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The content can&apos;t be null or white space..
        /// </summary>
        public static string ContentCantBeNullOrWhiteSpace {
            get {
                return ResourceManager.GetString("ContentCantBeNullOrWhiteSpace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The creator can&apos;t be null..
        /// </summary>
        public static string CreatorCantBeNull {
            get {
                return ResourceManager.GetString("CreatorCantBeNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The email can&apos;t be null or white space..
        /// </summary>
        public static string EmailCantBeNullOrWhiteSpace {
            get {
                return ResourceManager.GetString("EmailCantBeNullOrWhiteSpace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The email can&apos;t exceed {} characters..
        /// </summary>
        public static string EmailCantExceedXCharacters {
            get {
                return ResourceManager.GetString("EmailCantExceedXCharacters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The email must be a valid email address..
        /// </summary>
        public static string EmailMustBeValidEmailAddress {
            get {
                return ResourceManager.GetString("EmailMustBeValidEmailAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The name can&apos;t be null or white space..
        /// </summary>
        public static string NameCantBeNullOrWhiteSpace {
            get {
                return ResourceManager.GetString("NameCantBeNullOrWhiteSpace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The name can&apos;t exceed {} characters..
        /// </summary>
        public static string NameCantExceedXCharacters {
            get {
                return ResourceManager.GetString("NameCantExceedXCharacters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The name must be at least {} characters long..
        /// </summary>
        public static string NameMustBeAtLeastXCharactersLong {
            get {
                return ResourceManager.GetString("NameMustBeAtLeastXCharactersLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The password hash can&apos;t be null or white space..
        /// </summary>
        public static string PasswordHashCantBeNullOrWhiteSpace {
            get {
                return ResourceManager.GetString("PasswordHashCantBeNullOrWhiteSpace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The photo url can&apos;t be null or white space..
        /// </summary>
        public static string PhotoUrlCantBeNullOrWhiteSpace {
            get {
                return ResourceManager.GetString("PhotoUrlCantBeNullOrWhiteSpace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The photo url can&apos;t exceed {} characters..
        /// </summary>
        public static string PhotoUrlCantExceedXCharacters {
            get {
                return ResourceManager.GetString("PhotoUrlCantExceedXCharacters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The photo URL must be a valid HTTP or HTTPS url..
        /// </summary>
        public static string PhotoUrlMustBeValidHttpOrHttps {
            get {
                return ResourceManager.GetString("PhotoUrlMustBeValidHttpOrHttps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The publisher can&apos;t be null..
        /// </summary>
        public static string PublisherCantBeNull {
            get {
                return ResourceManager.GetString("PublisherCantBeNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The tag can&apos;t be null..
        /// </summary>
        public static string TagCantBeNull {
            get {
                return ResourceManager.GetString("TagCantBeNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The title can&apos;t be null or white space..
        /// </summary>
        public static string TitleCantBeNullOrWhiteSpace {
            get {
                return ResourceManager.GetString("TitleCantBeNullOrWhiteSpace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The title can&apos;t exceed {} characters..
        /// </summary>
        public static string TitleCantExceedXCharacters {
            get {
                return ResourceManager.GetString("TitleCantExceedXCharacters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The title must be at least {} characters long..
        /// </summary>
        public static string TitleMustBeAtLeastXCharactersLong {
            get {
                return ResourceManager.GetString("TitleMustBeAtLeastXCharactersLong", resourceCulture);
            }
        }
    }
}
